---
output:
  html_document: default
  pdf_document: default
params:
  chain: "HL"
---
```{r warning = FALSE, message = FALSE, cache = TRUE}

if(!require("ggplot2")){
  install.packages("ggplot2")
}
library(ggplot2)

if(!require("dplyr")) {
  install.packages("dplyr")
}
library(dplyr)

if(!require("arrow")) {
  install.packages("arrow")
}
library(arrow)

library(glue)
```

```{r cache = TRUE}
plot_seq_mean_attention <- function(data_mean, title) {
  light_chain_start <- 128

  # CDR1-3 region locations for IMGT taken from:
  # https://www.imgt.org/IMGTScientificChart/Nomenclature/IMGT-FRCDRdefinition.html
  cdr_regions <- data.frame(
    xmin = append(c(27, 56, 105), c(27, 56, 105) + light_chain_start),
    xmax = append(c(38, 65, 117), c(38, 65, 117) + light_chain_start),
    ymin = -Inf,
    ymax = Inf)

  ggplot(data_mean, aes(x = Seq_2, y = mean_attention, group = 1)) +
    geom_rect(data = cdr_regions,
              aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
              fill = "grey", alpha = 0.5, inherit.aes = FALSE) +
    geom_line(linetype = "solid") +
    labs(title = title) +
    theme_classic()
}

get_seq_mean_attention_data <- function(model, data_path) {
  chain <- params$chain

  data_ft <- read_parquet(file.path(data_path, glue("attention_weights_{model}_{chain}_FT.parquet")))
  data_pt <- read_parquet(file.path(data_path, glue("attention_weights_{model}_{chain}_PT.parquet")))

  chains <- unlist(strsplit(chain, ""))

  # Skip cross-chain pairs
  data_ft_mean <- data_ft %>%
    filter(Chain_1 == Chain_2, Chain_1 %in% chains) %>%
    group_by(Seq_2) %>%
    summarise(mean_attention = mean(Weight))

  data_pt_mean <- data_pt %>%
    filter(Chain_1 == Chain_2, Chain_1 %in% chains) %>%
    group_by(Seq_2) %>%
    summarise(mean_attention = mean(Weight))

  data_mean <- data_ft_mean
  data_mean$mean_attention <- data_ft_mean$mean_attention - data_pt_mean$mean_attention

  return(list(ft_mean = data_ft_mean, pt_mean = data_pt_mean, mean = data_mean))
}
```

```{r cache = TRUE}
data_path <- file.path(getwd(), "data")
```

```{r cache = TRUE}
model <- "AntiBERTa2"
data = get_seq_mean_attention_data(model, data_path)
```

```{r cache = TRUE}
plot_seq_mean_attention(data$ft_mean, glue("FT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$pt_mean, glue("PT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$mean, glue("FT - PT: {model}"))
```

```{r cache = TRUE}
model <- "AntiBERTy"
data = get_seq_mean_attention_data(model, data_path)
```

```{r cache = TRUE}
plot_seq_mean_attention(data$ft_mean, glue("FT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$pt_mean, glue("PT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$mean, glue("FT - PT: {model}"))
```

```{r cache = TRUE}
model <- "BALM-paired"
data = get_seq_mean_attention_data(model, data_path)
```

```{r cache = TRUE}
plot_seq_mean_attention(data$ft_mean, glue("FT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$pt_mean, glue("PT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$mean, glue("FT - PT: {model}"))
```

```{r cache = TRUE}
model <- "ESM2-8M"
data = get_seq_mean_attention_data(model, data_path)
```

```{r cache = TRUE}
plot_seq_mean_attention(data$ft_mean, glue("FT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$pt_mean, glue("PT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$mean, glue("FT - PT: {model}"))
```

```{r cache = TRUE}
model <- "ESM2-35M"
data = get_seq_mean_attention_data(model, data_path)
```

```{r cache = TRUE}
plot_seq_mean_attention(data$ft_mean, glue("FT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$pt_mean, glue("PT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$mean, glue("FT - PT: {model}"))
```

```{r cache = TRUE}
model <- "ESM2-150M"
data = get_seq_mean_attention_data(model, data_path)
```

```{r cache = TRUE}
plot_seq_mean_attention(data$ft_mean, glue("FT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$pt_mean, glue("PT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$mean, glue("FT - PT: {model}"))
```

```{r cache = TRUE}
model <- "ESM2-650M"
data = get_seq_mean_attention_data(model, data_path)
```

```{r cache = TRUE}
plot_seq_mean_attention(data$ft_mean, glue("FT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$pt_mean, glue("PT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$mean, glue("FT - PT: {model}"))
```

```{r cache = TRUE}
model <- "ft-ESM2"
data = get_seq_mean_attention_data(model, data_path)
```

```{r cache = TRUE}
plot_seq_mean_attention(data$ft_mean, glue("FT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$pt_mean, glue("PT: {model}"))
```

```{r cache = TRUE}
plot_seq_mean_attention(data$mean, glue("FT - PT: {model}"))
```
