---
title: "Token classification metrics"
output:
  html_document: default
  pdf_document: default
params:
  chain: "H"
  models: ""
  data_path: !r file.path(getwd(), "data")
---
```{r setup, warning = FALSE, message = FALSE, cache = FALSE}
if(!require("jsonlite")) {
  install.packages("jsonlite")
}
library(jsonlite)

if(!require("dplyr")) {
  install.packages("dplyr")
}
library(dplyr)

if(!require("ggplot2")) {
  install.packages("ggplot2")
}
library(ggplot2)

if(!require("stringr")) {
  install.packages("stringr")
}
library(stringr)

if(!require("tidyr")) {
  install.packages("tidyr")
}
library(tidyr)

if(!require("glue")) {
  install.packages("glue")
}
library(glue)
```

```{r plot_metrics, cache = FALSE}
plot_metrics <- function(model_name, is_ft) {
  chain <- params$chain
  fine_tuning_region <- params$fine_tuning_region
  predict_region <- params$predict_region
  data_path <- params$data_path

  ft_pt <- if (is_ft) "FT" else "PT"
  fine_tuning_region <- "FULL"

  metrics_all = data.frame()
  for (predict_region in c("FULL", "CDR1", "CDR2", "CDR3")) {
    json_file <- file.path(
      data_path,
      glue("token_predict_metrics_{model_name}_{chain}_{fine_tuning_region}_",
           "{predict_region}_{ft_pt}.json"))

    json_data <- fromJSON(json_file, flatten = TRUE)

    data <- data.frame(
      model_name = json_data$model_name,
      model_path = ifelse(is.null(json_data$model_path), NA,
                          json_data$model_path),
      num_parameters = json_data$num_parameters,
      test_loss = json_data$test_loss,
      accuracy = json_data$accuracy
    )

    metrics <- json_data[names(json_data) %in% c("weighted avg")]
    metrics_df <- bind_rows(metrics, .id = "metric_type")

    data <- metrics_df %>% bind_cols(data)

    metrics_long <- metrics_df %>%
      select(metric_type, `f1-score`, precision, recall) %>%
      pivot_longer(cols = c(`f1-score`, precision, recall),
                   names_to = "metric",
                   values_to = "value")
    metrics_long$region = predict_region

    metrics_all <- rbind(metrics_all, metrics_long)
  }

  rows_order <- c("f1-score", "precision", "recall")

  p <- ggplot(metrics_all, aes(x = region,
                               y = factor(metric, levels = rev(rows_order)),
                               fill = value)) +
    geom_tile(color = "black") +
    geom_text(aes(label = sprintf("%.2f", value)),
              color = "black", size = 3) +
    coord_fixed() +
    scale_fill_gradient(low = "#FFFFBF", high = "#D7301F") +
    scale_y_discrete(position = "left", labels = c(
      "f1-score" = "F1",
      "recall" = "Recall",
      "precision" = "Precision"
    )) +
    labs(
      title = glue(
        "{model_name} - {chain} - ",
        "{ft_pt}"),
      x = "Region",
      y = NULL,
      fill = NULL
    ) +
    theme_minimal() +
    theme(
      legend.position = "none",
      plot.title = element_text(hjust = 0.5),
      panel.grid = element_blank(),
      axis.text.x = element_text(color = "black"),
      axis.text.y = element_text(color = "black")
    )
  p
}
```

```{r plot_models, cache = FALSE}
models <- str_split(params$models, ",")[[1]]

for (model in models) {
  p1 <- plot_metrics(model, FALSE)
  p2 <- plot_metrics(model, TRUE)
  print(model)
  print(p1)
  print(p2)
}
```
