---
title: "Token classification"
output:
  html_document: default
  pdf_document: default
params:
  chain: "H"
  fine_tuning_region: "FULL"
  predict_region: "FULL"
  max_sequences: 0
  models: ""
  data_path: !r file.path(getwd(), "data")
---
```{r setup, warning = FALSE, message = FALSE, cache = FALSE}
if(!require("ggplot2")){
  install.packages("ggplot2")
}
library(ggplot2)

if(!require("dplyr")) {
  install.packages("dplyr")
}
library(dplyr)

if(!require("arrow")) {
  install.packages("arrow")
}
library(arrow)

if(!require("gridExtra")) {
  install.packages("gridExtra")
}
library(gridExtra)

if(!require("glue")) {
  install.packages("glue")
}
library(glue)

# For mixedsort()
if(!require("gtools")) {
  install.packages("gtools")
}

if(!require("tidyr")) {
  install.packages("tidyr")
}
library(tidyr)

if(!require("stringr")) {
  install.packages("stringr")
}
library(stringr)

if(!require("patchwork")){
  install.packages("patchwork")
}
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 14,
  fig.height = 16,
  dpi = 300
)
```

```{r plot_token_prediction, cache = FALSE}
# IMGT region locations taken from:
# https://www.imgt.org/IMGTScientificChart/Nomenclature/IMGT-FRCDRdefinition.html
REGIONS <- list(
  FR1  = c(1, 26),
  CDR1 = c(27, 38),
  FR2  = c(39, 55),
  CDR2 = c(56, 65),
  FR3  = c(66, 104),
  CDR3 = c(105, 117),
  FR4  = c(118, 129)
)

plot_bracket <- function(x1, x2, y_bar = 0.45, tip = 0.18,
                         label = NULL, gap = 0.08, lw = 0.6, text_vjust = 0,
                         text_size = 4) {
  list(
    annotate("segment", x = x1, xend = x2, y = y_bar, yend = y_bar,
             linewidth = lw),
    annotate("segment", x = x1, xend = x1, y = y_bar, yend = y_bar - tip,
             linewidth = lw),
    annotate("segment", x = x2, xend = x2, y = y_bar, yend = y_bar - tip,
             linewidth = lw),
    if (!is.null(label))
      annotate("text", x = (x1 + x2)/2, y = y_bar + gap, label = label,
               vjust = text_vjust, size = text_size)
  )
}

plot_token_prediction <- function(model_name, is_ft) {
  chain <- params$chain
  fine_tuning_region <- params$fine_tuning_region
  predict_region <- params$predict_region
  data_path <- params$data_path

  ft_pt <- if (is_ft) "FT" else "PT"
  token_pred_data_path <- file.path(
    data_path,
    glue("token_prediction_{model_name}_{chain}_{fine_tuning_region}_",
         "{predict_region}_{ft_pt}.parquet"))

  if(!file.exists(token_pred_data_path)) return()

  data <- read_parquet(token_pred_data_path)

  df <- data[, (names(data) %in%
             c("iden_code", "positions", "labels", "predicted_labels"))]

  pivoted_df <- df %>%
    separate_rows(positions, labels, predicted_labels, sep = ",") %>%
    mutate(labels = as.integer(labels),
           predicted_labels = as.integer(predicted_labels))

  aggregated_df <- pivoted_df %>%
    group_by(iden_code, positions) %>%
    summarise(
      labels = sum(labels, na.rm = TRUE),
      predicted_labels = sum(predicted_labels, na.rm = TRUE),
      .groups = 'drop'
    )

  if (params$max_sequences > 0)
    aggregated_df <- aggregated_df %>%
    filter(iden_code %in% (unique(iden_code) %>% head(params$max_sequences)))

  # Fill in missing values
  aggregated_df <- tidyr::complete(
    aggregated_df,
    positions = unique(aggregated_df$positions),
    iden_code = unique(aggregated_df$iden_code)
  )

  aggregated_df$pred_labels_diff <- with(
    aggregated_df,
    ifelse(is.na(labels), -100,
      ifelse(labels == predicted_labels, labels,
        ifelse(predicted_labels == 1 & labels != predicted_labels, 2,
          ifelse(predicted_labels == 0 & labels != predicted_labels, 3,
            ifelse(predicted_labels == -100 &
                   labels != predicted_labels, 4, NA))))))

  # Sort positions by number followed by iCode
  aggregated_df$positions <- factor(
    aggregated_df$positions, levels = mixedsort(
      unique(aggregated_df$positions)))

  position_breaks <- levels(aggregated_df$positions)[
    grepl("[A-Z]$", levels(aggregated_df$positions)) |
      (suppressWarnings(as.numeric(levels(
        aggregated_df$positions)) %% 5 == 0)) |
      (suppressWarnings(as.numeric(levels(aggregated_df$positions)) == 1))]

  position_labels <- sapply(levels(aggregated_df$positions), function(x)
    if (x %in% position_breaks)
      x
    else
      "")

  p <- ggplot(aggregated_df,
               aes(x = positions, y = iden_code,
                   fill = factor(pred_labels_diff,
                                 levels = c(1, 0, 2, 3, -100)))) +
    geom_tile() +
    scale_fill_manual(values = c(
        "-100" = "#6bd2db",
        "0" = "#0ea7b5",
        "1" = "#ffbe4f",
        "2" = "#766df6",
        "3" = "#f66d6d"
      ),
      labels = c(
        "-100" = "Missing sequence position",
        "0" = "Correct non-binding prediction",
        "1" = "Correct binding prediction",
        "2" = "False positive",
        "3" = "False negative"
    )) +
    labs(
      title = NULL,
      x = glue("Chain: {chain} - {predict_region}"),
      y = "Sequences",
      fill = "Color"
    ) +
    scale_x_discrete(
      labels = position_labels, guide = guide_axis(n.dodge = 2)) +
    theme(
      plot.title = element_text(hjust = 0.5),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.text.x = element_text(
        angle = 90,
        hjust = 1,
        vjust = 0.5,
        size = 5
      )
    )

  p_brackets <- ggplot(aggregated_df, aes(x = positions, y = 0)) +
    geom_blank() +
    coord_cartesian(ylim = c(0, 1), clip = "off") +
    theme_void()

  x_levels <- levels(factor(aggregated_df$positions))
  for (region in names(REGIONS)) {
    start <- which(x_levels == toString(REGIONS[[region]][1]))
    if(length(start) == 0) next

    end <- which(x_levels == toString(REGIONS[[region]][2]))
    if(length(end) == 0) {
      end <- length(x_levels)
    }

    p_brackets <- p_brackets + plot_bracket(
      start, end, y_bar = 0.2, tip = 0.2, label = region, gap = 0.1)
  }

  p <- p_brackets / p + plot_layout(heights = unit(c(12, 1), c("mm", "null"))) +
   plot_annotation(title = glue(
     "Predicted labels - {model_name} - {fine_tuning_region} - ",
     "{predict_region} - {ft_pt}")) &
    theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))

  print(p)
}
```

```{r plot_models, cache = FALSE, fig.height = 4.7}
models <- str_split(params$models, ",")[[1]]

for (model in models) {
  print(model)
  plot_token_prediction(model, FALSE)
  plot_token_prediction(model, TRUE)
}
```
