---
title: "Attention comparison"
output:
  html_document: default
  pdf_document: default
params:
  chain: "H"
  models: ""
  models_per_row: 5
  data_path: !r file.path(getwd(), "data")
---
```{r setup, warning = FALSE, message = FALSE, cache = FALSE}

if(!require("ggplot2")){
  install.packages("ggplot2")
}
library(ggplot2)

if(!require("dplyr")) {
  install.packages("dplyr")
}
library(dplyr)

if(!require("arrow")) {
  install.packages("arrow")
}
library(arrow)

if(!require("glue")){
  install.packages("glue")
}
library(glue)

if(!require("stringr")) {
  install.packages("stringr")
}
library(stringr)

if(!require("patchwork")) {
  install.packages("patchwork")
}
library(patchwork)

if(!require("rlist")) {
  install.packages("rlist")
}
library(rlist)

knitr::opts_chunk$set(
  dpi = 300
)
```

```{r functions, cache = FALSE}
data_path <- params$data_path

plot_seq_mean_attention <- function(data_mean, title) {
  if("H" %in% params$chain) {
    xmin <- c(27, 56, 105)
    xmax <- c(38, 65, 117)
  } else {
    xmin <- c()
    xmax <- c()
  }
  if("L" %in% params$chain) {
    light_chain_start <- 128
    xmin <- append(xmin, c(27, 56, 105) + light_chain_start)
    xmax <- append(xmax, c(38, 65, 117) + light_chain_start)
  }

  # CDR1-3 region locations for IMGT taken from:
  # https://www.imgt.org/IMGTScientificChart/Nomenclature/IMGT-FRCDRdefinition.html
  cdr_regions <- data.frame(
    xmin = xmin,
    xmax = xmax,
    ymin = -Inf,
    ymax = Inf)

  p <- ggplot(data_mean, aes(x = Seq_2, y = mean_attention, group = 1)) +
    geom_rect(data = cdr_regions,
              aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
              fill = "grey", alpha = 0.5, inherit.aes = FALSE) +
    geom_line(linetype = "solid") +
    labs(title = title, y = "Mean attention", x = "Sequence") +
    theme_classic()

  p
}

get_seq_mean_attention_data <- function(model, data_path) {
  chain <- params$chain

  data_ft <- read_parquet(file.path(data_path, glue("attention_weights_{model}_{chain}_FT.parquet")))
  data_pt <- read_parquet(file.path(data_path, glue("attention_weights_{model}_{chain}_PT.parquet")))

  chains <- unlist(strsplit(chain, ""))

  # Skip cross-chain pairs
  data_ft_mean <- data_ft %>%
    filter(Chain_1 == Chain_2, Chain_1 %in% chains) %>%
    group_by(Seq_2) %>%
    summarise(mean_attention = mean(Weight))

  data_pt_mean <- data_pt %>%
    filter(Chain_1 == Chain_2, Chain_1 %in% chains) %>%
    group_by(Seq_2) %>%
    summarise(mean_attention = mean(Weight))

  data_mean <- data_ft_mean
  data_mean$mean_attention <- data_ft_mean$mean_attention - data_pt_mean$mean_attention

  return(list(ft_mean = data_ft_mean, pt_mean = data_pt_mean, mean = data_mean))
}

plot_model_attention_data <- function(model) {
  data = get_seq_mean_attention_data(model, data_path)
  p1 <- plot_seq_mean_attention(data$ft_mean, glue("FT: {model}"))
  p2 <- plot_seq_mean_attention(data$pt_mean, glue("PT: {model}"))
  p3 <- plot_seq_mean_attention(data$mean, glue("FT - PT: {model}"))

  list(ft = p1, pt = p2, ft_pt = p3)
}

set_plots_for_grid <- function(p, models_per_row, i) {
  p$ft <- p$ft + labs(title = model, x = NULL) +
    theme(plot.title = element_text(size = 10),
          axis.title.y = element_text(size = 8))
  p$pt <- p$pt + labs(title = NULL, x = NULL) +
    theme(axis.title.y = element_text(size = 8))
  p$ft_pt <- p$ft_pt + labs(title = NULL, x = "Sequence") +
    theme(axis.title.x = element_text(size = 8),
          axis.title.y = element_text(size = 8))

  if (i %% models_per_row == 0) {
    p$ft <- p$ft + labs(y = "Mean attention (FT)")
    p$pt <- p$pt + labs(y = "Mean attention (PT)")
    p$ft_pt <- p$ft_pt + labs(y = "Mean attention (FT-PT)")
  } else {
    p$ft <- p$ft + labs(y = NULL)
    p$pt <- p$pt + labs(y = NULL)
    p$ft_pt <- p$ft_pt + labs(y = NULL)
  }

  p
}

print_plot_grid <- function(plots, num_plot_groups) {
  for (i in 1:num_plot_groups) {
    pg = plots[[i]]

    row1 <- lapply(pg, `[[`, "ft") |> wrap_plots(ncol = length(pg))
    row2 <- lapply(pg, `[[`, "pt") |> wrap_plots(ncol = length(pg))
    row3 <- lapply(pg, `[[`, "ft_pt") |> wrap_plots(ncol = length(pg))

    plot_grid <- row1 / row2 / row3
    print(plot_grid)
  }
}
```

```{r plot_models, cache = FALSE}
models <- str_split(params$models, ",")[[1]]

models_per_row <- params$models_per_row
num_plot_groups <- ceiling(length(models) / models_per_row)
plots <- replicate(num_plot_groups, list(), simplify = FALSE)

i <- 0
for (model in models) {
  print(model)
  p <- plot_model_attention_data(model)
  print(p$ft)
  print(p$pt)
  print(p$ft_pt)

  p <- set_plots_for_grid(p, models_per_row, i)

  j <- floor(i / models_per_row) + 1
  plots[[j]] <- list.append(plots[[j]], p)

  i <- i + 1
}

print_plot_grid(plots, num_plot_groups)
```
