---
title: "Token classification metrics"
output:
  html_document: default
  pdf_document: default
params:
  chain: "H"
  models: ""
  bar_chart_region: "FULL"
  data_path: !r file.path(getwd(), "data")
---
```{r setup, warning = FALSE, message = FALSE, cache = FALSE}
if(!require("jsonlite")) {
  install.packages("jsonlite")
}
library(jsonlite)

if(!require("dplyr")) {
  install.packages("dplyr")
}
library(dplyr)

if(!require("ggplot2")) {
  install.packages("ggplot2")
}
library(ggplot2)

if(!require("stringr")) {
  install.packages("stringr")
}
library(stringr)

if(!require("tidyr")) {
  install.packages("tidyr")
}
library(tidyr)

if(!require("glue")) {
  install.packages("glue")
}
library(glue)

knitr::opts_chunk$set(
  dpi = 300
)
```

```{r plot_metrics, cache = FALSE}
add_mean_value <- function(metrics_all, columns, mean_region_name) {
  metrics_all <- metrics_all %>%
    filter(region %in% columns) %>%
    group_by(group, metric) %>%
    summarise(
      value = mean(value, na.rm = TRUE),
      region = mean_region_name,
      .groups = "drop"
    ) %>%
    bind_rows(metrics_all, .)
  metrics_all
}

load_data <- function(model_name, is_ft) {
  chain <- params$chain
  fine_tuning_region <- params$fine_tuning_region
  predict_region <- params$predict_region
  data_path <- params$data_path

  ft_pt <- if (is_ft) "FT" else "PT"
  fine_tuning_region <- "FULL"

  predict_regions <- c("FULL", "FR1", "CDR1", "FR2",
                       "CDR2", "FR3", "CDR3", "FR4")

  metrics_all = data.frame()
  for (predict_region in predict_regions) {
    json_file <- file.path(
      data_path,
      glue("token_predict_metrics_{model_name}_{chain}_{fine_tuning_region}_",
           "{predict_region}_{ft_pt}.json"))

    if(!file.exists(json_file)) next

    json_data <- fromJSON(json_file, flatten = TRUE)

    if (!"1" %in% names(json_data)) {
      json_data[["1"]] <- list(
        precision  = 0.0,
        recall     = 0.0,
        `f1-score` = 0.0,
        support    = 0.0
      )
    }

    data <- data.frame(
      model_name = json_data$model_name,
      model_path = ifelse(is.null(json_data$model_path), NA,
                          json_data$model_path),
      num_parameters = json_data$num_parameters,
      test_loss = json_data$test_loss,
      accuracy = json_data$accuracy,
      balanced_accuracy = json_data$balanced_accuracy,
      ap = json_data$ap,
      auc = if (!is.null(json_data$auc)) json_data$auc else 0,
      mcc = json_data$mcc,
      fpr = json_data$fpr,
      f1_weighted = json_data$f1_weighted
    )

    metrics <- json_data[names(json_data) %in% c(
      "0", "1", "weighted avg", "macro avg")]

    metrics_df <- bind_rows(metrics, .id = "group")

    metrics_long <- metrics_df %>%
      select(group, `f1-score`, precision, recall, support) %>%
      pivot_longer(cols = c(`f1-score`, precision, recall, support),
                   names_to = "metric",
                   values_to = "value")
    metrics_long$region = predict_region

    metrics_all <- rbind(metrics_all, metrics_long)

    for(metric in c("accuracy", "balanced_accuracy",
                    "ap", "auc", "mcc", "fpr", "f1_weighted")) {
      new_row <- data.frame(group = "global",
                            metric = metric,
                            value = data[[metric]],
                            region = predict_region)
      metrics_all <- rbind(metrics_all, new_row)
    }
  }

  if(nrow(metrics_all) > 0) {
    metrics_all <- add_mean_value(metrics_all,
                                  c("CDR1", "CDR2", "CDR3"),
                                  "CDRm")
    metrics_all <- add_mean_value(metrics_all,
                                  c("FR1", "FR2", "FR3", "FR4"),
                                  "FRm")
  }

  metrics_all
}

plot_metrics <- function(data, model_name, is_ft, metrics_group) {
  chain <- params$chain
  ft_pt <- if (is_ft) "FT" else "PT"

  data <- subset(data, group == metrics_group & metric != "support")

  regions_order <- c("FR1", "CDR1", "FR2", "CDR2", "FR3", "CDR3", "FR4", "FULL",
                     "CDRm", "FRm")
  metrics_order <- c("f1-score", "precision", "recall", "accuracy",
                     "balanced_accuracy", "ap", "auc", "mcc", "fpr",
                     "f1_weighted")

  p <- ggplot(data, aes(x = factor(region, levels = regions_order),
                        y = factor(metric, levels = rev(metrics_order)),
                        fill = value)) +
    geom_tile(color = "black") +
    geom_text(aes(label = sprintf("%.2f", value)),
              color = "black", size = 3) +
    coord_fixed() +
    scale_fill_gradient(low = "#FFFFBF", high = "#D7301F") +
    scale_y_discrete(position = "left", labels = c(
      "f1-score" = "F1",
      "recall" = "Recall",
      "precision" = "Precision",
      "accuracy" = "Accuracy",
      "balanced_accuracy" = "Balanced Accuracy",
      "ap" = "AP",
      "auc" = "AUC",
      "mcc" = "MCC",
      "fpr" = "FPR",
      "f1_weighted" = "F1 Weighted"
    )) +
    labs(
      title = glue(
        "{model_name} - {chain} - {stringr::str_to_title(metrics_group)} ",
        "- {ft_pt}"),
      x = NULL,
      y = NULL,
      fill = NULL
    ) +
    theme_minimal() +
    theme(
      legend.position = "right",
      plot.title = element_text(hjust = 0.5),
      panel.grid = element_blank(),
      axis.text.x = element_text(color = "black"),
      axis.text.y = element_text(color = "black")
    ) +
    guides(fill = guide_colorbar(title.position = "top",
                                 barwidth = unit(0.5, "lines"),
                                 barheight = unit(5, "lines")))
  p
}

plot_support <- function(data, model_name, is_ft) {
  chain <- params$chain
  ft_pt <- if (is_ft) "FT" else "PT"

  regions_order <- c("FR1", "CDR1", "FR2", "CDR2", "FR3", "CDR3", "FR4", "FULL",
                     "CDRm", "FRm")
  groups = c("1", "0", "weighted avg")

  data = subset(data, metric == "support" & group %in% groups)

  p <- ggplot(data, aes(x = factor(region, levels = regions_order),
                        y = factor(group, levels = rev(groups)),
                        fill = value)) +
    geom_tile(color = "black") +
    geom_text(aes(label = sprintf("%.0f", value)),
              color = "black", size = 3) +
    coord_fixed() +
    scale_fill_gradient(low = "#deebf7", high = "#3182bd") +
    scale_y_discrete(position = "left", labels = c(
      "0" = "Non-binding",
      "1" = "Binding",
      "weighted avg" = "Total"
    )) +
    labs(
      title = glue(
        "{model_name} - {chain} - {ft_pt} - Support"),
      x = NULL,
      y = NULL,
      fill = NULL
    ) +
    theme_minimal() +
    theme(
      legend.position = "none",
      plot.title = element_text(hjust = 0.5),
      panel.grid = element_blank(),
      axis.text.x = element_text(color = "black"),
      axis.text.y = element_text(color = "black")
    )
  p
}

plot_metrics_bar_chart <- function(data, metric, group) {
  chain <- params$chain
  region <- params$bar_chart_region
  paragraph_model_name <- "Paragraph"

  # New vars needed to avoid naming collisions in filter(...)
  var_metric <- metric
  var_region <- region
  var_group <- group

  df <- data %>%
    filter(metric == var_metric,
           region == var_region,
           group == var_group,
           (ft == TRUE | model == paragraph_model_name)) %>%
    mutate(
      model = reorder(model, value),
      ft_label = ifelse(model == paragraph_model_name, paragraph_model_name,
                        ifelse(ft, "FT", "PT"))
    )

  ggplot( df, aes(x = model, y = value, fill = ft_label)) +
    geom_col(position = position_dodge(width = 0.60), width = 0.80) +
    labs(
      title = glue(
        "{str_to_title(metric)} - {chain} - {str_to_title(group)} - {region}"),
      x = "Model",
      y = str_to_title(metric),
      fill = "Model Type"
    ) +
    scale_fill_manual(
      values = c(
        "PT" = "#aec7e8",
        "FT" = "#1f77b4",
        "Paragraph" = "#ff7f0e"),
      labels = c(
        "PT" = "Pre-trained AbLM/PLM",
        "FT" = "Fine-tuned AbLM/PLM",
        paragraph_model_name = paragraph_model_name)
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.title  = element_text(hjust = 0.5))
}
```

```{r plot_models, cache = FALSE}
models <- str_split(params$models, ",")[[1]]
all_data <- data.frame()

for (model in models) {
  print(model)
  for (ft in c(TRUE, FALSE)) {
    data <- load_data(model, ft)
    if(nrow(data) == 0) next

    for (metrics_group in c("0", "1", "weighted avg", "macro avg", "global")) {
      p <- plot_metrics(data, model, ft, metrics_group)
      print(p)
    }
    p <- plot_support(data, model, ft)
    print(p)

    data$ft <- ft
    data$model <- model
    all_data <- rbind(all_data, data)
  }
}

for (group in c("0", "1", "weighted avg", "macro avg")) {
  for (metric in c("f1", "precision", "recall")) {
    p <- plot_metrics_bar_chart(all_data, metric, group)
    print(p)
  }
}
```
